name: CI Pipeline    #nombre visible en la pestaña de Actions

on:    #eventos que dispara el workflow

  push:  # cuando alguien hace push
    branches: [ main ] #...a la rama main
  
  pull_request:   #cuando alguien hace pull request (pr)
    branches: [ main ] #..... a la rama main

  workflow_dispatch:   #permite ejecución manual desde la UI

# Variables a nivel del workflow
env:
  NODE_VERSION: "20"
  APP_NAME: cron-ticker

jobs:

  build:
    runs-on: ubuntu-latest

    # Variables a nivel del job
    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Show Variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ env.NODE_VERSION }}"
      
      - name: Show Github Variables
        run: |
          echo "App Version: ${{ vars.APP_VERSION }}"

      # agregar la variable node version

      - name: Show Github Node Version
        run: |
          echo "Node Version from Github variable ${{ vars.NODE_VERSION }}"

      - name: Deploy API
        run: | 
          echo "Deploy with key ${{ secrets.API_KEY }}"

      #Variables a nivel del step
      - name: Build
        run: npm run build
        env:
          APP_VERSION: '2.0.0'